### ISSUE TITLE
Tuple error

### ISSUE THREAD

**Issue by Realist-Git** [mekkablue/InsertInflections#1]
10.10.2
glyphs v.799 

I get the following message when I run insert inflections from Filter Menu. The inflection points are still added, and I am unaware why the func prompts an error.

Here is an image with a bit more details.
![insert_inflections](https://cloud.githubusercontent.com/assets/13359955/9771225/5a381cb2-573d-11e5-9116-0df36b422fc8.png)

**Comment by mekkablue** [comment]
Looking into it.

**Comment by mekkablue** [comment]
The latest update should fix this problem.
