### ISSUE TITLE
to run this filters for paths inside selected nodes only

### ISSUE THREAD

**Issue by synthview** [mekkablue/InsertInflections#2]
Hello!
could it be possible to have this filter to apply only on paths between selected nodes? Sometimes I want to add only 1 inflection somewhere. Especially with multimasters, adding points everywhere isn’t useful.

Thanks :)

**Comment by mekkablue** [comment]
You can Shift-click on an inflecting segment with the Draw tool (P). A plugin should not reduplicate on-board functionality.
